# Generated by Django 3.2.6 on 2021-08-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='adduser',
            name='confirm_password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='adduser',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
